name: actionlint

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [staging]
    paths:
      - '.github/workflows/**'

jobs:
  action-lint:
    runs-on: ubuntu-latest
    name: Action Lint
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install action linter
        run: |
          mkdir -p ~/bin
          curl -sL https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash | bash -s -- latest ~/bin

      - name: Check that all workflows are valid
        run: |
          set -xe
          find .github/workflows -type f -name '*.yaml' -print0 | xargs --null ~/bin/actionlint
