name: buildenvs/base

on:
  push:
    branches:
      - stable

jobs:
  gcc:
    strategy:
      matrix:
        include:
          - GCC_ARCH: x86_64
            GCC_VERSION: 12.2.0
            GCC_SUFFIX:
          # - GCC_ARCH: arm
          #   GCC_VERSION: 12.2.0
          #   GCC_SUFFIX:
          # - GCC_ARCH: arm64
          #   GCC_VERSION: 12.2.0
          #   GCC_SUFFIX:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to OCI registry
        uses: docker/login-action@v2
        with:
          registry: index.unikraft.io
          username: ${{ secrets.REG_USERNAME }}
          password: ${{ secrets.REG_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          file: ./buildenvs/gcc.Dockerfile
          tags: index.unikraft.io/kraftkit.sh/gcc:${{ matrix.GCC_VERSION }}-${{ matrix.GCC_ARCH }}${{ matrix.GCC_SUFFIX }}
          platforms: linux/amd64
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}
        env:
          UK_ARCH: ${{ matrix.GCC_ARCH }}

  qemu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - QEMU_VERSION: 7.1.0

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to OCI registry
        uses: docker/login-action@v2
        with:
          registry: index.unikraft.io
          username: ${{ secrets.REG_USERNAME }}
          password: ${{ secrets.REG_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          file: ./buildenvs/qemu.Dockerfile
          tags: index.unikraft.io/kraftkit.sh/qemu:${{ matrix.QEMU_VERSION }}
          platforms: linux/amd64
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}

  myself:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to OCI registry
        uses: docker/login-action@v2
        with:
          registry: index.unikraft.io
          username: ${{ secrets.REG_USERNAME }}
          password: ${{ secrets.REG_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          file: ./buildenvs/myself.Dockerfile
          tags: index.unikraft.io/kraftkit.sh/myself:latest
          platforms: linux/amd64
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}
  
  base:
    runs-on: ubuntu-latest
    needs: [gcc, qemu, myself]

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to OCI registry
        uses: docker/login-action@v2
        with:
          registry: index.unikraft.io
          username: ${{ secrets.REG_USERNAME }}
          password: ${{ secrets.REG_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: index.unikraft.io/kraftkit.sh/base:latest
          platforms: linux/amd64
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}
