name: tools/protoc-gen-go-netconn

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: staging
    paths:
      - 'tools/protoc-gen-go-netconn/**'
      - '.github/workflows/gobuild-protoc.yaml'

jobs:
  unit:
    runs-on: ubuntu-latest
    container: kraftkit.sh/myself-full:latest
    name: Build Check
    env:
      RUNGOGENERATE: false
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-go@v2
        with:
          go-version: "1.20.2"

      - name: Build protoc-gen-go-netconn
        run: |
          set -xe
          git config --global --add safe.directory /__w/kraftkit/kraftkit
          go build -o dist/ ./tools/protoc-gen-go-netconn/...

      - name: Run Help Message
        run: |
          set -xe
          ./dist/protoc-gen-go-netconn -h
