name: buildenvs/myself-full

# Build only on changes to the build environment itself
on:
  push:
    branches:
      - stable
      - staging
    paths:
      - 'buildenvs/myself.Dockerfile'
      - '.github/workflows/myself-full.yaml'

jobs:
  myself-full-push:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Registry
        if: ${{ github.event_name == 'push' }}
        uses: docker/login-action@v2
        with:
          registry: index.unikraft.io
          username: ${{ secrets.REG_USERNAME }}
          password: ${{ secrets.REG_TOKEN }}

      - name: Build OCI image
        uses: docker/build-push-action@v4
        with:
          push: false
          file: ./buildenvs/myself.Dockerfile
          tags: kraftkit.sh/myself-full:latest
          target: kraftkit-full
          platforms: linux/amd64
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=docker,dest=/tmp/myself.tar

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v2
        with:
          name: oci-images
          path: /tmp/myself-full.tar

      - name: Push OCI Image
        uses: docker/build-push-action@v4
        if: ${{ github.event_name == 'push' }}
        with:
          push: true
          tags: index.unikraft.io/kraftkit.sh/myself-full:latest
          target: kraftkit-full
          platforms: linux/amd64
          file: ./buildenvs/myself.Dockerfile
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}
